### ISSUE TITLE
Bug: Missing all "half" D/Ts.

### ISSUE THREAD

**Issue by PleuPleu** [mmendelson222/geocaching-fizzy#1]
Tested this program and like the idea but all caches with a "half" D/T does not show up on the D/T-grid for me. So no D/T 1.5/1.5 only 1/1, 1/2 and so on. I did a small test modifying the My Finds-file and changing the dot to a comma on one cache made that cache show up in the grid. So the problem seem to be that .gpx has "2.5" but program requires "2,5". Attached printscreen shows before and after the edit of the gpx.

![qwaesrtyui - kopia](https://user-images.githubusercontent.com/86418996/123276754-c022f000-d505-11eb-927e-ff262a3d6652.jpg)

![awesrdtfyguhij - kopia](https://user-images.githubusercontent.com/86418996/123276760-c0bb8680-d505-11eb-8331-bb991f487777.jpg)

**Comment by mmendelson222** [comment]
How interesting.  Can do two things for me?

1. Make sure you're working with the most recent version of the program
2. email me (or attach here) your myfinds file so I can duplicate the issue.   Then I'd be happy to take a look. 

Just to add:  In my myfinds gpx, the d/t data looks like this for each cache:
```
      <groundspeak:difficulty>2.5</groundspeak:difficulty>
      <groundspeak:terrain>1</groundspeak:terrain>
```
...and it works for me.     Happy to investigate though, once I have your info.

**Comment by PleuPleu** [comment]
> How interesting. Can do two things for me?
> 
> 1. Make sure you're working with the most recent version of the program
> 2. email me (or attach here) your myfinds file so I can duplicate the issue.   Then I'd be happy to take a look.
> 
> Just to add: In my myfinds gpx, the d/t data looks like this for each cache:
> 
> ```
>       <groundspeak:difficulty>2.5</groundspeak:difficulty>
>       <groundspeak:terrain>1</groundspeak:terrain>
> ```
> 
> ...and it works for me. Happy to investigate though, once I have your info.

I just downloaded the program for the first time ever today so I would assume it's the most recent version? :) 
My D/T data looks the same but I had to edit it to <groundspeak:difficulty>2,5</groundspeak:difficulty> to make it show up in the D/T-grid. I've tried with the myfinds from other accounts too and I have the same problem for all myfinds-files I've tried. Here's a file with the same issue, only 25 founds and the 6 T1.5 and 1 T2.5 doesn't show up in the D/T-grid but the 18 1/1s show.

**Comment by mmendelson222** [comment]
OK, I think I know the issue.  In the US we use "." as the decimal separator.   Some countries use the comma.   

I set the "default language" for the app to English, that should resolve the problem. 

Can you download the new version and try again?

**Comment by PleuPleu** [comment]
Of course, I should have figured that out! I've seen similar issues in other things. :) Works like a charm, thanks for fixing it so quickly!

**Comment by mmendelson222** [comment]
PleuPleu's myfinds gpx is located here:  https://github.com/mmendelson222/geocaching-fizzy/files/6711308/23946175.zip

**Comment by PleuPleu** [comment]
> PleuPleu's myfinds gpx is located here: https://github.com/mmendelson222/geocaching-fizzy/files/6711308/23946175.zip

The point of this? I removed it because 1) It's not my myfinds per se but a myfinds I was looking at when I saw the issue. 2) It doesn't seem relevant when the issue is fixed?

**Comment by mmendelson222** [comment]
Hi PleuPleu - It's useful now because a similar issue has come up with another cacher, although the issue is not documented here yet and has not been fully investigated. 

As for the file - it's actually still there, but I guess you removed the link.  I just put it here for reference.
