### ISSUE TITLE
Object Reference Error

### ISSUE THREAD

**Issue by zstatman** [mmendelson222/geocaching-fizzy#2]
Eager to try your informative app but when run get an error (attached picture), hit OK then a blank results screen displays.

Generated the gpx out of GSAK that contains ALL finds regardless of type, i.e., geocaches, terracaches and opencaches so that could be the reason.

If so, would be great if could include this approach

Tks
Z

![2021-07-29_0743](https://user-images.githubusercontent.com/1054303/127486744-54d197be-becb-4bb9-bf3d-1408dd1d262c.jpg)

**Comment by mmendelson222** [comment]
Hi Z, 

I assume you're experiencing this error when you're loading the gpx file.  

This app only operates on the GPX generated by your My Finds query.  The schema is very specific.  So while the GSAK output is also GPX, I'm sure the schema is different from what you get with My Finds.   

I'd be interested in the GPX file that you're trying to load.  Would you mind posting it here?  Or just email it to me if you prefer. 

I suspect that this use case is a pretty complex one, but I'm willing to take a look.   If it contains all the same information as the My Finds GPX, it would be possible.

**Comment by zstatman** [comment]
Thanks for checking Michael and attached is a GSAK gpx with as sub-set but all cache sites

 

Take care

Will

**Comment by zstatman** [comment]
Attached zip file just in case
[tempcaches.zip](https://github.com/mmendelson222/geocaching-fizzy/files/6902332/tempcaches.zip)


W
